version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres_todo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"